import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:3000/users/sign_in');
  await page.getByRole('link', { name: 'Sign Up' }).click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('Mikuchan@gmail.com');
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).fill('miku1234');
  await page.getByLabel('Password confirmation').dblclick();
  await page.getByLabel('Password confirmation').fill('miku1234');
  await page.getByRole('button', { name: 'Sign up' }).click();
  await page.getByText('Welcome to the Cyberpunk').click();
  await page.locator('div').filter({ hasText: 'Welcome to the Cyberpunk' }).getByRole('link').click();
  await page.getByLabel('Title').click();
  await page.getByLabel('Title').fill('Minecraft');
  await page.getByLabel('Content').click();
  await page.getByLabel('Content').press('ArrowRight');
  await page.getByLabel('Content').press('ArrowRight');
  await page.getByLabel('Content').press('ArrowRight');
  await page.getByLabel('Content').press('ArrowRight');
  await page.getByLabel('Content').fill('who want to play together');
  await page.getByRole('button', { name: 'Create Post' }).click();
  await page.getByPlaceholder('Write a comment...').click();
  await page.getByPlaceholder('Write a comment...').fill('anybody?');
  await page.getByRole('button', { name: 'Add Comment' }).click();
  await page.getByRole('button', { name: 'Like' }).click();
  await page.getByRole('link', { name: 'Edit Post' }).click();
  await page.getByLabel('Title').click();
  await page.getByLabel('Title').fill('Minecraft2');
  await page.getByRole('button', { name: 'Update Post' }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByPlaceholder('Search for posts...').click();
  await page.getByPlaceholder('Search for posts...').fill('minecraft');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('link', { name: 'Show' }).click();
  await page.getByRole('button', { name: 'Log Out' }).click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('Mikuchan@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('miku123');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('mi');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('miku1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
});